# Generated by Django 3.2 on 2021-04-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activity_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
